### ISSUE TITLE
`bitbake mono -c devshell` fails

### ISSUE THREAD

**Issue by cmcqueen** [DynamicDevices/meta-mono#47]
On Yocto warrior.

I tried to do:

    bitbake mono -c devshell

I got an error:

```
ERROR: mono-6.10.0.104-r0 do_devshell: Unable to spawn terminal auto: Execution of '/home/craigm/yocto-warrior/poky/scripts/oe-gnome-terminal-phonehome /tmp/tmp1ez4483g /home/craigm/yocto-warrior/poky/build/tmp/work/armv7at2hf-neon-poky-linux-gnueabi/mono/6.10.0.104-r0/temp/run.do_terminal.38492' failed with exit code 1:
Failed to import the site module
Traceback (most recent call last):
  File "/usr/lib/python3.6/site.py", line 570, in <module>
    main()
  File "/usr/lib/python3.6/site.py", line 556, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python3.6/site.py", line 288, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python3.6/site.py", line 264, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python3.6/site.py", line 254, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python3.6/sysconfig.py", line 607, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python3.6/sysconfig.py", line 550, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python3.6/sysconfig.py", line 421, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata'

ERROR: mono-6.10.0.104-r0 do_devshell: 
ERROR: mono-6.10.0.104-r0 do_devshell: Function failed: do_devshell
ERROR: Logfile of failure stored in: /home/craigm/yocto-warrior/poky/build/tmp/work/armv7at2hf-neon-poky-linux-gnueabi/mono/6.10.0.104-r0/temp/log.do_devshell.38492
ERROR: Task (/home/craigm/yocto-warrior/poky/build/../../meta-mono/recipes-mono/mono/mono_6.10.0.104.bb:do_devshell) failed with exit code '1'
```

**Comment by ajlennon** [comment]
Closing this due to lack of correspondence - feel free to reopen if it's still an issue
